### ISSUE TITLE
[FEAT]: Run sotopia wo Redis

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#60]
### Description

Currently, it looks like even if we provide an external dataset, the Redis still requests to connect to a database. This behavior is not good for extending Sotopia to other projects.

**Comment by ProKil** [comment]
What do you mean by external dataset? As long as they can be converted into the EnvironmentProfile/AgentProfile format, they should be able to be saved onto Redis. 

If they cannot be converted into those formats, the problem is not on Redis? It is best to describe the specific use case and we can find a way to support that.

**Comment by ProKil** [comment]
I added a [colab example](https://colab.research.google.com/drive/14hJOfzpA37PRUzdlFgiqVzUGIhhngqnz?usp=sharing) for setting up Redis for Sotopia. It is actually very straightforward. Feel free to reopen if there is a compelling use case where Redis the bottleneck for extending sotopia
